[phases.setup]
nixPkgs = ['nodejs_18', 'npm-9_x']

[phases.install]
cmds = [
  'npm ci',
  'npx playwright install chromium --with-deps'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm start' 